from flask import Flask, render_template_string
app = Flask(__name__)
HTML = """<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jacona</title><script src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js"></script><style>body{background:#111;color:#fff;font-family:sans-serif;padding:10px}.card{background:#222;padding:12px;border-radius:12px;max-width:500px;margin:auto;text-align:center} canvas{width:100%;background:#fff;border-radius:10px;margin-top:10px} button{background:#00ff88;color:#000;border:0;padding:10px;width:100%;border-radius:8px;font-weight:bold;margin-top:6px}.b2{background:#444;color:#fff} input{width:100%}</style></head><body><div class="card"><h3>JACONA PRO</h3><input type="file" id="f" accept="image/*"><canvas id="c"></canvas><canvas id="o" style="display:none"></canvas><div style="display:flex;gap:5px"><button class="b2" onclick="setF('bw')">B/N</button><button class="b2" onclick="setF('color')">Color</button><button class="b2" onclick="setF('orig')">Original</button></div><label>Brillo</label><input type="range" id="br" min="0" max="200" value="100"><label>Color</label><input type="range" id="co" min="0" max="300" value="100"><div style="display:flex;gap:5px"><button class="b2" id="bb" onclick="tog()">Borrar OFF</button><button class="b2" onmousedown="ver(1)" onmouseup="ver(0)" ontouchstart="ver(1)" ontouchend="ver(0)">Ver Antes</button></div><button onclick="down()">DESCARGAR</button><p style="font-size:11px;color:#888">1. Activa Borrar (rojo) 2. Pinta la mancha con el dedo</p></div><script>
let can=document.getElementById('c'),ctx=can.getContext('2d'),canO=document.getElementById('o'),ctxO=canO.getContext('2d'),img=new Image(),bor=false,pin=false,fil='orig',br=document.getElementById('br'),co=document.getElementById('co');
document.getElementById('f').onchange=e=>{let r=new FileReader();r.onload=x=>{img.src=x.target.result};r.readAsDataURL(e.target.files[0])};
img.onload=()=>{can.width=canO.width=img.width;can.height=canO.height=img.height;ctxO.drawImage(img,0,0);draw()};
function setF(f){fil=f;draw()}
function draw(){if(!img.src)return;ctx.clearRect(0,0,can.width,can.height);ctx.fillStyle='#fff';ctx.fillRect(0,0,can.width,can.height);let s=`brightness(${br.value}%) saturate(${co.value}%)`;if(fil=='bw')s+=' grayscale(100%)';if(fil=='color'){ctx.filter=s+' grayscale(100%)';ctx.drawImage(img,0,0);ctx.globalCompositeOperation='color';ctx.fillStyle='#c07a3a';ctx.globalAlpha=0.4;ctx.fillRect(0,0,can.width,can.height);ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;return}ctx.filter=s;ctx.drawImage(img,0,0);ctx.filter='none'}
br.oninput=draw;co.oninput=draw;
function tog(){bor=!bor;let b=document.getElementById('bb');b.textContent=bor?'Borrar ON':'Borrar OFF';b.style.background=bor?'#ff4444':'#444'}
function ver(v){if(v){ctx.clearRect(0,0,can.width,can.height);ctx.drawImage(canO,0,0)}else{draw()}}
can.addEventListener('mousedown',e=>{if(!bor)return;pin=true;era(e)});can.addEventListener('mousemove',e=>{if(!bor||!pin)return;era(e)});can.addEventListener('touchstart',e=>{if(!bor)return;pin=true;era(e.touches[0])});can.addEventListener('touchmove',e=>{if(!bor||!pin)return;e.preventDefault();era(e.touches[0])},{passive:false});window.addEventListener('mouseup',()=>pin=false);window.addEventListener('touchend',()=>pin=false);
function era(e){let r=can.getBoundingClientRect();let x=(e.clientX-r.left)*(can.width/r.width);let y=(e.clientY-r.top)*(can.height/r.height);ctx.globalCompositeOperation='source-over';ctx.fillStyle='#ffffff';ctx.beginPath();ctx.arc(x,y,20,0,6.28);ctx.fill()}
function down(){let a=document.createElement('a');a.download='foto_jacona.png';a.href=can.toDataURL();a.click()}
</script></body></html>"""
@app.route('/')
def home(): return render_template_string(HTML)
